version: "3"
services: 
    api:
        container_name: syeta_api
        build: .
        ports: 
            - 8000:8000
        volumes: 
            - ./api:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        depends_on: 
            - db
    db:
        container_name: syeta_db
        image: mysql:5.7.22
        restart: always
        environment:
            MYSQL_DATABASE: django_admin
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
        - 33006:3306
      
        volumes:
        - .dbdata:/var/lib/mysql